services:
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: tweaty-eureka
    ports:
      - "19090:19090"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: tweaty-gateway
    ports:
      - "19091:19091"
    depends_on:
      - eureka

  db:
    container_name: tweaty-db
    image: postgres
    volumes:
      - tweaty-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  tweaty-data:

networks:
  mynetwork:
    driver: bridge
