spring:
  application:
    name: store-service

  datasource:
    url: jdbc:postgresql://tweaty-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/



