spring:
  application:
    name: notification-service
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectionTimeout: 10000
          timeout: 20000
          starttls:
            enable: true
