spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
#  profiles:
#    active: local


server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
    register-with-eureka: true
    fetch-registry: true



