#spring:
#  application:
#    name: gateway-service
#  profiles:
#    active: local
#

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/
    register-with-eureka: true
    fetch-registry: true



