#spring:
#  application:
#    name: eureka-service
#  profiles:
#    active: local



spring:
  application:
    name: eureka

server:
  port: 19090

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:19090/eureka/