spring:
  application:
    name: auth-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: tweaty-bucket
  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

feign:
  okhttp:
    enabled: true

jwt:
  secret: ${JWT_SECRET}