spring:
  application:
    name: reservation-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tweaty-db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: tweaty-redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
server:
  port: ${RESERVATION_SERVER_PORT}
