server:
  port: ${COUPON_SERVER_PORT}
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100

spring:
  config:
    import: optional:file:.env[properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:10000
    topics:
      coupon-create: time-attack-coupon-create
      coupon-issued: coupon-issued
    groups:
      coupon-create: timeAttack-coupon-create
      coupon-issued: coupon-issued

  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
